configure terminal
router bgp 100
 neighbor 10.0.12.3 remote-as 200
 neighbor 10.0.14.3 remote-as 200
 !
 address-family ipv4 unicast
  network 192.168.10.0/24
  neighbor 10.0.12.3 route-map PERMIT-ALL in
  neighbor 10.0.12.3 route-map PERMIT-ALL out
  neighbor 10.0.14.3 route-map PERMIT-ALL in
  neighbor 10.0.14.3 route-map PERMIT-ALL out
 exit-address-family
exit
route-map PERMIT-ALL permit 10
end
