configure terminal
router bgp 200
 neighbor 10.0.23.2 remote-as 200
 neighbor 10.0.35.3 remote-as 300
 !
 address-family ipv4 unicast
  network 10.0.35.0/29
  neighbor 10.0.23.2 next-hop-self
  neighbor 10.0.35.3 next-hop-self
  neighbor 10.0.35.3 route-map PERMIT-ALL in
  neighbor 10.0.35.3 route-map PERMIT-ALL out
 exit-address-family
exit
route-map PERMIT-ALL permit 10
end
