configure terminal
router bgp 200
 neighbor 10.0.14.2 remote-as 100
 neighbor 10.0.24.2 remote-as 200
 neighbor 10.0.45.3 remote-as 300
 !
 address-family ipv4 unicast
  neighbor 10.0.24.2 next-hop-self
  neighbor 10.0.14.2 route-map PERMIT-ALL in
  neighbor 10.0.14.2 route-map PERMIT-ALL out
  neighbor 10.0.45.3 route-map PERMIT-ALL in
  neighbor 10.0.45.3 route-map PERMIT-ALL out
 exit-address-family
exit
route-map PERMIT-ALL permit 10
end
